### PR TITLE
add group type 'dots' so that we get the right font w/o special casing group type 'op'

### PR DESCRIPTION
**Pull request by k4b7**
dots

Green is LaTeX and red is KaTeX.  The last two lines use `\dots` whereas the first is `\dotsb` and the second is `\dotsi`.  The issue with the second line is a pre-existing issue.

### CODE REVIEW

**Comment by edemaine** [comment]
This works, but I was vaguely hoping to do it via the macro system (so that the produced content is identical to the effect of typing `\cdots` or whatever). Of course, I haven't had time to do that yet, so maybe this is worth going with...

**Comment by k4b7** [comment]
I don't think our support for macros is powerful enough b/c we need to know what the next token is and then somehow use that to decide which version of dots to render.

**Comment by edemaine** [comment]
Yes, but I think it'd be worth adding support for that to the macro parser.  I wasn't planning on implementing `\futurelet`, but rather allow `defineMacro` to give a function which gets a context that has a `nextToken` equivalent of `\futurelet`... Of course, at that point, maybe I'm just implementing `defineFunction`?

**Comment by edemaine** [comment]
Maybe the `dots` function should recursively call the parser to get the output of `\cdots` and `\ldots`? Is that crazy?

**Pull request merged**
